#!/bin/sh
set -e

for d in \
  /usr/local/texlive/2025/tlpkg \
  /usr/local/texlive/2025/texmf-var \
  /usr/local/texlive/2025/texmf-dist
do
  if [ -d "$d" ]; then
    chgrp -R www-data "$d"
    chmod -R g+rwX "$d"
  fi
done

if [ -d /var/lib/overleaf ]; then
  mkdir -p /var/lib/overleaf/system
  chgrp -R www-data /var/lib/overleaf/system
  chmod -R g+rwX /var/lib/overleaf/system
fi

echo "Checking texlive images"
cd /overleaf/services/web
/sbin/setuser www-data node modules/server-ce-scripts/scripts/check-texlive-images.mjs
